bu: networks
projects:
  tenant1_net_gcp_prod:
    name: tenant1_net_gcp_prod
    description:
    gcp_project_id: hc-74c5998971954543b85856b66ab
    team_project_access:
      tenant1_net_gcp_prod_maintain:
        team:
          access: "maintain"
      tenant1_net_gcp_prod_write:
        team:
          access: "write"
  tenant1_net_aws_prod:
    name: tenant1_net_aws_prod
    description: tenant1 networks aws prod
    enable_oidc: aws
    team_project_access:
      tenant1_net_aws_prod_maintain:
        team:
          access: "maintain"
      tenant1_net_aws_prod_write:
        team:
          access: "write"
  tenant1_net_aws_test:
    name: tenant1_net_aws_test
    description: tenant1 networks aws test
    enable_oidc: aws
    team_project_access:
      tenant1_net_aws_test_maintain:
        team:
          access: "maintain"
  tenant2_net_aws_prod:
    name: tenant2_net_aws_prod
    description: 
    enable_oidc: aws
    team_project_access:
      tenant2_net_aws_prod_maintain:
        team:
          access: "maintain"
      tenant2_net_aws_prod_write:
        team:
          access: "write"