workspace_name: bu1_data_plaform1_ws
project_name: bu1_data_plaform1
create_repo: false
create_variable_set: false
vcs_repo:
  identifier: hashi-demo-lab/bu1_data_plaform1_ws
  branch: main
variables:
      datazone_domain_name:
        category: terraform
        description:
        hcl: false
        sensitive: false
        value: bu1_data_plaform1