workspace_name: tenant1_net_gcp_prod_ws
project_name: networks_tenant1_net_gcp_prod
create_repo: false
create_variable_set: false
vcs_repo:
  identifier: hashi-demo-lab/network-gcp-example
  branch: main
variables:
      network_yaml_file:
        category: terraform
        description:
        hcl: false
        sensitive: false
        value: tenant1_net_gcp_prod.yaml